# Generated by Django 5.0.4 on 2026-09-09 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_condition",
                    models.CharField(
                        choices=[
                            ("pairwise", "Pairwise choice"),
                            ("ranking", "Rank ten films"),
                        ],
                        max_length=20,
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["started_at"],
            },
        ),
        migrations.CreateModel(
            name="ElicitationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("pairwise", "Pairwise choice"),
                            ("ranking", "Rank ten films"),
                        ],
                        max_length=20,
                    ),
                ),
                ("block", models.PositiveSmallIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                ("film_indices", models.JSONField()),
                ("presented_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="project4.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["block", "position"],
                "unique_together": {("participant", "block", "position")},
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.JSONField()),
                ("duration_ms", models.PositiveIntegerField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="project4.elicitationtask",
                    ),
                ),
            ],
        ),
    ]
