# Generated by Django 5.0.4 on 2026-09-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project4", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={"ordering": ["started_at", "id"]},
        ),
    ]
