# Generated by Django 5.0.4 on 2026-09-05 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="uploads/")),
                ("target", models.CharField(max_length=200)),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("classification", "Classification"),
                            ("regression", "Regression"),
                        ],
                        max_length=20,
                    ),
                ),
                ("n_rows", models.PositiveIntegerField()),
                ("n_features", models.PositiveIntegerField()),
                ("dropped_columns", models.JSONField(default=list)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_key", models.CharField(max_length=50)),
                ("hyperparameter", models.CharField(max_length=50)),
                ("values", models.JSONField()),
                ("scores", models.JSONField()),
                ("test_size", models.FloatField()),
                ("random_state", models.IntegerField()),
                ("scoring", models.CharField(max_length=30)),
                ("best_value", models.FloatField()),
                ("best_score", models.FloatField()),
                ("automated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="project1.dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
