# Generated by Django 5.0.4 on 2026-09-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project1", "0002_alter_dataset_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrun",
            name="selection_score",
            field=models.FloatField(default=0.0),
        ),
    ]
